# Generated by Django 6.0.6 on 2026-09-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'UserDetail', 'verbose_name_plural': 'UserDetails'},
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Sirname',
            new_name='Surname',
        ),
    ]
