# Generated by Django 6.0.6 on 2026-09-02 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0002_alter_userdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='Surname',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=350),
            preserve_default=False,
        ),
    ]
